#!/bin/bash

# AgentMesh Local Development Startup Script
# Runs infrastructure in Docker, applications locally

set -e

# Get the project root directory (parent of scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

echo "🚀 Starting AgentMesh Local Development Environment"
echo "=================================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Please install Docker first."
    exit 1
fi

if ! command -v python3.12 &> /dev/null && ! command -v python3 &> /dev/null; then
    echo "❌ Python 3.12+ not found. Please install Python first."
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo "❌ npm not found. Please install Node.js first."
    exit 1
fi

echo "✅ Prerequisites OK"
echo ""

# ---------------------------------------------------------------------------
# Create local .env files for each service
# ---------------------------------------------------------------------------
create_local_env() {
    local service_path=$1
    local service_name=$2
    
    # Get values from root .env or use defaults
    local postgres_user=$(grep "^POSTGRES_USER=" .env 2>/dev/null | cut -d '=' -f2 || echo "agentmesh")
    local postgres_pass=$(grep "^POSTGRES_PASSWORD=" .env 2>/dev/null | cut -d '=' -f2 || echo "agentmesh")
    local postgres_db=$(grep "^POSTGRES_DB=" .env 2>/dev/null | cut -d '=' -f2 || echo "agentmesh")
    
    cat > "$service_path/.env" <<ENVEOF
# Auto-generated by start-local.sh for local development
# Apps run on HOST, infrastructure in Docker

ENVIRONMENT=local
LOG_LEVEL=DEBUG
LOG_FORMAT=console

# Database (localhost - Docker port mapping)
POSTGRES_HOST=localhost
POSTGRES_PORT=5433
POSTGRES_USER=${postgres_user}
POSTGRES_PASSWORD=${postgres_pass}
POSTGRES_DB=${postgres_db}

# OpenSearch (localhost)
OPENSEARCH_HOST=localhost
OPENSEARCH_PORT=9200
OPENSEARCH_USER=admin
OPENSEARCH_PASSWORD=Agentmesh#2026
OPENSEARCH_USE_SSL=false
OPENSEARCH_EMBEDDING_DIM=1536

# Redis (localhost)
REDIS_HOST=localhost
REDIS_PORT=6379

# MinIO Storage (localhost)
STORAGE_BACKEND=minio
STORAGE_ENDPOINT_URL=http://localhost:9000
STORAGE_ACCESS_KEY=minioadmin
STORAGE_SECRET_KEY=minioadmin
STORAGE_BUCKET=agentmesh-uploads

# Agent Configuration
AGENT_FRAMEWORK=langgraph
AGENT_PROVIDER=anthropic
AGENT_MODEL=claude-sonnet-4-6
AGENT_TEMPERATURE=0.2
AGENT_ENABLE_LONG_TERM_MEMORY=true

# Ingestion
INGESTION_EMBEDDING_PROVIDER=openai
INGESTION_EMBEDDING_MODEL=text-embedding-3-small
SEARCH_PROVIDER=auto

# LiteLLM (localhost)
LITELLM_ENABLED=true
LITELLM_BASE_URL=http://localhost:4000
LITELLM_MASTER_KEY=sk-agentmesh-local

# MongoDB (localhost)
VECTOR_BACKEND=opensearch
MONGODB_URI=mongodb://localhost:27017
MONGODB_DATABASE=agentmesh

# MCP Servers (localhost when running locally)
MCP_DOCUMENTS_URL=http://localhost:8081
MCP_SEARCH_URL=http://localhost:8082
MCP_MEMORY_URL=http://localhost:8083

# Phoenix (localhost)
PHOENIX_ENABLED=true
PHOENIX_HOST=localhost
PHOENIX_GRPC_PORT=4317
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317

# Neo4j (localhost)
NEO4J_URI=bolt://localhost:7687
NEO4J_AUTH=neo4j/agentmesh

# Opik (disabled)
OPIK_ENABLED=false

# Service URLs
BACKEND_URL=http://localhost:8000
INGESTION_SERVICE_URL=http://localhost:8001
ENVEOF

    # Append API keys from root .env if it exists
    if [ -f .env ]; then
        echo "" >> "$service_path/.env"
        echo "# API Keys (from root .env)" >> "$service_path/.env"
        grep -E "^(OPENAI_API_KEY|ANTHROPIC_API_KEY|GOOGLE_API_KEY|TAVILY_API_KEY)=" .env >> "$service_path/.env" 2>/dev/null || true
    fi
    
    echo "   ✓ Created $service_name .env file"
}

echo "📝 Creating local .env files..."
create_local_env "backend" "backend"
create_local_env "agentservices/ingestion/ingestion-service" "ingestion-service"
create_local_env "agentservices/mcp/mcp-documents" "mcp-documents"
create_local_env "agentservices/mcp/mcp-search" "mcp-search"
create_local_env "agentservices/mcp/mcp-memory" "mcp-memory"
echo ""

# Start infrastructure services
echo -e "${BLUE}🐳 Starting infrastructure services (Docker)...${NC}"
docker compose -f docker-compose-infra.yml up -d 2>&1 | grep -v "Pulling" || true

echo "⏳ Waiting for services to be healthy (30s)..."
sleep 30

# Check infrastructure health
echo "🏥 Checking infrastructure health..."
docker compose -f docker-compose-infra.yml ps postgres redis opensearch minio

echo ""
echo -e "${GREEN}✅ Infrastructure services started${NC}"
echo ""
echo "📊 Service URLs:"
echo "  - PostgreSQL: localhost:5432"
echo "  - Redis: localhost:6379"
echo "  - OpenSearch: http://localhost:9200"
echo "  - MinIO Console: http://localhost:9001"
echo "  - Phoenix (Observability): http://localhost:6006"
echo ""

# Check if virtual environments exist
echo -e "${BLUE}🐍 Setting up Python environments...${NC}"

if [ ! -d "backend/.venv" ]; then
    echo "Creating backend virtual environment..."
    cd backend
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -q --upgrade pip
    pip install -q -r requirements.txt
    cd ..
fi

if [ ! -d "agentservices/ingestion/ingestion-service/.venv" ]; then
    echo "Creating ingestion-service virtual environment..."
    cd agentservices/ingestion/ingestion-service
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -q --upgrade pip
    pip install -q -r requirements.txt
    cd ../../..
fi

echo -e "${GREEN}✅ Python environments ready${NC}"
echo ""

# Check if frontend dependencies are installed
if [ ! -d "frontend/node_modules" ]; then
    echo -e "${BLUE}📦 Installing frontend dependencies...${NC}"
    cd frontend
    npm install
    cd ..
    echo -e "${GREEN}✅ Frontend dependencies installed${NC}"
    echo ""
fi

# Run database migrations
echo -e "${BLUE}🗃️  Running database migrations...${NC}"
cd backend

# Check if .env file exists
if [ ! -f .env ]; then
    echo "❌ backend/.env not found. This shouldn't happen."
    exit 1
fi

# Activate venv and run migrations
source .venv/bin/activate

# Load .env variables safely (without xargs which fails on special chars)
set -a  # Automatically export all variables
source .env 2>/dev/null || true
set +a

# Run migrations
echo "Running alembic migrations..."
if alembic upgrade head 2>&1 | tail -10; then
    echo -e "${GREEN}✅ Database migrations complete${NC}"
else
    echo -e "${YELLOW}⚠️  Database migration had issues (check connection settings)${NC}"
    echo "Debug: POSTGRES_HOST=$POSTGRES_HOST, POSTGRES_PORT=$POSTGRES_PORT"
fi

cd ..
echo ""

echo "=================================================="
echo -e "${GREEN}🎉 Infrastructure ready! Now start your applications:${NC}"
echo ""
echo -e "${YELLOW}Open separate terminals and run:${NC}"
echo ""
echo "1️⃣  Backend:"
echo "   cd backend && source .venv/bin/activate"
echo "   uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
echo ""
echo "2️⃣  Ingestion Service:"
echo "   cd agentservices/ingestion/ingestion-service && source .venv/bin/activate"
echo "   uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
echo ""
echo "3️⃣  Celery Worker:"
echo "   cd agentservices/ingestion/ingestion-service && source .venv/bin/activate"
echo "   celery -A app.worker.celery_app worker --loglevel=INFO --concurrency=2 -Q ingest,default"
echo ""
echo "4️⃣  Frontend:"
echo "   cd frontend"
echo "   npm run dev"
echo ""
echo "5️⃣  MCP Servers (optional):"
echo "   cd agentservices/mcp/mcp-documents && source .venv/bin/activate && python -m app.server"
echo "   cd agentservices/mcp/mcp-search && source .venv/bin/activate && python -m app.server"
echo "   cd agentservices/mcp/mcp-memory && source .venv/bin/activate && python -m app.server"
echo ""
echo "=================================================="
echo ""
echo -e "${BLUE}💡 Quick commands:${NC}"
echo "  - Stop infrastructure: docker compose -f docker-compose-infra.yml down"
echo "  - View logs: docker compose -f docker-compose-infra.yml logs -f <service>"
echo "  - Check status: docker compose -f docker-compose-infra.yml ps"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"
